# Generated by Django 5.2.14 on 2026-05-06 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='enterprise.enterprise'),
        ),
        migrations.AddField(
            model_name='department',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='enterprise.enterprise'),
        ),
        migrations.AddField(
            model_name='branch',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='enterprise.enterprise'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('enterprise', 'employee_code'), name='unique_employee_code_per_enterprise'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('enterprise', 'branch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('enterprise', 'name')},
        ),
    ]
