# Generated by Django 6.0.4 on 2026-04-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='device_identifier',
        ),
    ]
