# Generated by Django 6.0.4 on 2026-05-02 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_delete_userprofile_remove_employee_device_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='default_arrival_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='default_departure_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
    ]
