# Generated by Django 6.0.4 on 2026-05-02 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_enterprise_default_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='department',
            name='departure_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='default_arrival_time',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='default_departure_time',
        ),
    ]
