# Generated by Django 5.2.14 on 2026-05-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_alter_employee_employee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_format_preference',
            field=models.CharField(choices=[('ad', 'Gregorian (AD)'), ('bs', 'Nepali (BS)')], default='ad', help_text='User preferred date format for attendance reports and UI', max_length=2),
        ),
    ]
