# Generated by Django 5.2.14 on 2026-05-06 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_employee_date_format_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_format_preference',
        ),
    ]
