# Generated by Django 6.0.4 on 2026-04-29 13:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.PositiveSmallIntegerField(choices=[(0, 'Check-In'), (1, 'Check-Out'), (2, 'Break-Out'), (3, 'Break-In'), (4, 'OT-In'), (5, 'OT-Out')])),
                ('event_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device_serial', models.CharField(blank=True, max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='device', max_length=32)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to='enterprise.employee')),
            ],
            options={
                'ordering': ['event_time', 'id'],
                'indexes': [models.Index(fields=['employee', 'event_time'], name='attendance__employe_7affdc_idx'), models.Index(fields=['event_type', 'event_time'], name='attendance__event_t_b4857d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(db_index=True)),
                ('first_check_in', models.DateTimeField(blank=True, null=True)),
                ('last_check_out', models.DateTimeField(blank=True, null=True)),
                ('first_break_out', models.DateTimeField(blank=True, null=True)),
                ('last_break_in', models.DateTimeField(blank=True, null=True)),
                ('first_ot_in', models.DateTimeField(blank=True, null=True)),
                ('last_ot_out', models.DateTimeField(blank=True, null=True)),
                ('worked_minutes', models.PositiveIntegerField(default=0)),
                ('present', models.BooleanField(default=False)),
                ('last_event_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Check-In'), (1, 'Check-Out'), (2, 'Break-Out'), (3, 'Break-In'), (4, 'OT-In'), (5, 'OT-Out')], null=True)),
                ('last_event_time', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='enterprise.employee')),
            ],
            options={
                'ordering': ['-attendance_date', 'employee__name'],
                'indexes': [models.Index(fields=['attendance_date', 'employee'], name='attendance__attenda_1609d7_idx')],
                'unique_together': {('employee', 'attendance_date')},
            },
        ),
    ]
