# Generated by Django 5.2.14 on 2026-05-06 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceevent',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to='enterprise.employee'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='enterprise.employee'),
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['employee', 'event_time'], name='attendance__employe_7affdc_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['event_type', 'event_time'], name='attendance__event_t_b4857d_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['attendance_date', 'employee'], name='attendance__attenda_1609d7_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['attendance_date_bs', 'employee'], name='attendance__attenda_82d933_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendance',
            unique_together={('employee', 'attendance_date')},
        ),
    ]
