# Generated by Django 6.0.4 on 2026-05-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyattendance',
            name='first_break_out',
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='last_break_in',
        ),
    ]
