# Generated by Django 5.2.14 on 2026-05-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_dailyattendance_first_break_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='attendance_date_bs_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='attendance_date_bs_month',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='attendance_date_bs_year',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
    ]
