# Generated by Django 5.2.14 on 2026-05-06 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_dailyattendance_attendance_date_bs_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyattendance',
            name='attendance_date_bs_day',
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='attendance_date_bs_month',
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='attendance_date_bs_year',
        ),
    ]
