# Generated by Django 5.2.14 on 2026-05-06 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_devices', to='enterprise.branch'),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_devices', to='enterprise.enterprise'),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='device.biometricdevice'),
        ),
        migrations.AddField(
            model_name='employeebiometricmapping',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_mappings', to='device.biometricdevice'),
        ),
        migrations.AddField(
            model_name='employeebiometricmapping',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_mappings', to='enterprise.employee'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['device', 'status'], name='device_devi_device__75fd18_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['status', '-created_at'], name='device_devi_status_2354ed_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebiometricmapping',
            index=models.Index(fields=['device', 'device_user_id'], name='device_empl_device__71cb05_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebiometricmapping',
            index=models.Index(fields=['employee', 'device'], name='device_empl_employe_7e2ef4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeebiometricmapping',
            unique_together={('device', 'device_user_id')},
        ),
    ]
